on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build dll for release
      run: msbuild ide/vs2019/mimalloc-override.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:OutDir=c:\out
    
    - name: Saving build files
      uses: actions/upload-artifact@v3
      with:
        name: c-out
        path: c:\out
